=== nf-core/sarek/assets/schema_snpsift_databases.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/nf-core/sarek/master/assets/schema_snpsift_databases.json",
    "title": "nf-core/sarek - params.snpsift_databases schema",
    "description": "Schema for the SnpSift annotation databases CSV samplesheet",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "vcf": {
                "type": "string",
                "pattern": "^\\S+\\.vcf(\\.gz)?$",
                "errorMessage": "VCF file path must be provided and end with .vcf or .vcf.gz",
                "format": "file-path",
                "exists": true
            },
            "tbi": {
                "type": "string",
                "pattern": "^\\S+\\.tbi$",
                "errorMessage": "Index file must end with .tbi",
                "format": "file-path"
            },
            "fields": {
                "type": "string",
                "errorMessage": "Comma-separated INFO field names to extract"
            },
            "prefix": {
                "type": "string",
                "errorMessage": "Prefix for annotated field names"
            },
            "vardb": {
                "type": "string",
                "format": "directory-path",
                "errorMessage": "Path to pre-built .snpsift.vardb directory"
            }
        },
        "required": ["vcf"]
    }
}

=== nf-core/sarek/tests/config/snpsift_test_databases.json
[
    {
        "vcf": "https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/sarscov2/illumina/vcf/test2.vcf.gz",
        "tbi": "https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/sarscov2/illumina/vcf/test2.vcf.gz.tbi",
        "fields": "DP,VDB,MQB,BQB",
        "prefix": "TEST_"
    }
]

=== nf-core/sarek/assets/snpsift_databases_example.json
[
    {
        "vcf": "/path/to/annotations/dbsnp/dbsnp_156.vcf.gz",
        "tbi": "/path/to/annotations/dbsnp/dbsnp_156.vcf.gz.tbi",
        "fields": "RS,COMMON,SAO",
        "prefix": "dbSNP_"
    },
    {
        "vcf": "/path/to/annotations/gnomad/gnomad.genomes.v4.0.sites.vcf.gz",
        "tbi": "/path/to/annotations/gnomad/gnomad.genomes.v4.0.sites.vcf.gz.tbi",
        "fields": "AF,AC,AN,nhomalt",
        "prefix": "gnomAD_"
    },
    {
        "vcf": "/path/to/annotations/clinvar/clinvar_20240101.vcf.gz",
        "tbi": "/path/to/annotations/clinvar/clinvar_20240101.vcf.gz.tbi",
        "fields": "CLNSIG,CLNDN,CLNREVSTAT",
        "prefix": "ClinVar_"
    },
    {
        "vcf": "/path/to/annotations/1000genomes/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5c.20130502.sites.vcf.gz",
        "tbi": "/path/to/annotations/1000genomes/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5c.20130502.sites.vcf.gz.tbi",
        "fields": "AF,AC,AN,EAS_AF,EUR_AF,AFR_AF,AMR_AF,SAS_AF",
        "prefix": "1000G_"
    },
    {
        "vcf": "/path/to/annotations/cosmic/cosmic_v99.vcf.gz",
        "tbi": "/path/to/annotations/cosmic/cosmic_v99.vcf.gz.tbi",
        "fields": "GENE,STRAND,CDS,AA,CNT",
        "prefix": "COSMIC_"
    },
    {
        "vcf": "/path/to/annotations/exac/ExAC.r1.sites.vep.vcf.gz",
        "tbi": "/path/to/annotations/exac/ExAC.r1.sites.vep.vcf.gz.tbi",
        "fields": "AF,AC,AN,AC_Adj,AN_Adj",
        "prefix": "ExAC_"
    },
    {
        "vcf": "/path/to/annotations/custom/my_custom_annotations.vcf.gz",
        "tbi": "/path/to/annotations/custom/my_custom_annotations.vcf.gz.tbi",
        "fields": "",
        "prefix": "Custom_"
    }
]
